version: '3.1'

services:
  backend:
    build:
      dockerfile: docker/Dockerfile-backend
      context: ".."
    ports:
      - "3000:3000"
    volumes:
      - "../backend/src:/app/src"
      - "../backend/ormconfig.js:/app/ormconfig.js"
    depends_on:
      - db_postgres
    networks:
      - backend
  db_postgres:
    image: postgres:alpine
    restart: always
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: example

networks:
  backend:
